# Generated by Django 4.2.7 on 2024-01-29 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mvideo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "продукты"},
        ),
    ]
